services:
  mongo:
    image: mongo:latest
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=qa
      - DB_NAME=schedio_qa
      - MONGO_URI=mongodb://mongo:27017/schedio_qa
    depends_on:
      - mongo

  frontend:
    build:
      context: ./schedio-frontend
      target: server
    ports:
      - "4100:80"
    environment:
      - NODE_ENV=qa
    depends_on:
      backend:
        condition: service_started
