services:
  mongo:
    image: mongo:latest

  backend:
    build:
      context: ./backend
      target: production
    command: node index.js
    environment:
      - NODE_ENV=qa
      - PORT=3000
      - DB_NAME=schedio_qa
      - MONGO_URI=mongodb://mongo:27017/schedio_qa
    depends_on:
      - mongo

  frontend:
    build:
      context: ./schedio-frontend
      target: server
    ports:
      - "4100:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
