FROM node:22-alpine

WORKDIR /app

# Copiar archivos de definición de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el código fuente
COPY . .

# Ejecutar las pruebas unitarias
CMD ["npm", "test"]
