
# Dockerfile.build para el Backend
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Verificar sintaxis/lint si es necesario, o preparar los siguientes pasos
# Solo una verificación de que las dependencias de construcción se pueden instalar

CMD ["npm", "ls"]
