# Dockerfile.prod for Frontend (Angular)
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Entorno de producción
FROM node:22-alpine

WORKDIR /app

# Copiar artefactos construidos desde la etapa de construcción
COPY --from=builder /app/dist ./dist

# Iniciar el servidor
CMD ["node", "dist/schedio-frontend/server/server.mjs"]
