FROM node:22-alpine

WORKDIR /app

# Copiar archivos de definición de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el código fuente
COPY . .

# Ejecutar las pruebas unitarias
# Se asume que "ng test" ejecuta los tests.
# --watch=false para ejecución única (CI)
CMD ["npm", "run", "test", "--", "--watch=false"]
